### ISSUE TITLE
Consider adding in `pre-commit`

### ISSUE THREAD

**Issue by jlward** [derekjamerson/Blackjack_Python#11]
[pre-commit](https://pypi.org/project/pre-commit/) is a lib that lets you auto-run things whenever you run `git commit`. Before my current job, I had never used it before, but I'm quite fond of it at this point. I generally include three things:

* `black`
* `isort`
* `flake8`

Black is a code formatter. It will give your code a consistent look and feel. ISort will sort your imports in a sane fashion. Flake8 will tell you if your code is in violation of any of the pep8 (general guidelines for python code formatting). 

It is my suggestion to include pre-commit and include some amount of these. If you choose to do this, I'll suggest updating the README to include directions for how to get it set up. Which is something that would be useful if more than just you is working on this. It's overkill. But it's also helpful as a learning experience.

**Comment by derekjamerson** [comment]
Still need to add README
