### ISSUE TITLE
Make `Card` sortable and sum able

### ISSUE THREAD

**Issue by jlward** [derekjamerson/Blackjack_Python#23]
If we can make `Card` sortable and sumable, then when we are calculating the score for a given hand, we can call `return sum(sorted(self.hand, reverse=True))`. Which is one line of code.

In order to do this I think we need to add two methods to `Card`:

* `__lt__`. This represents "less than" and I think it's the only thing needed in order to make sorting work. Because of magic and stuff. This should be fairly straight forward. There are examples on the internets about what this should look like.
* `__radd__`. When I initially had the the plan to do this, I assumed it would be `__add__`. I was wrong. `__add__` lets you add this object to another of this object. `__radd__` lets you call add between this object and something else. In our case, the something else is going to be an `int`. This method is where we are going to dynamically change the value of the ace based on the current count. In order for this to work when we sum the cards, we have to make sure the cards in sorted highest to lowest.

Once these two things are done, we'll be able to make the method on `player` to get the score be one line. 

I would like to see some tests on calculating the score. This is going to be the place in the code that is most likely to be busted. So having several tests on it would go a long way. Ping me if you need help with these.

**Comment by derekjamerson** [comment]
These methods (__add__, __repr__, etc) are interesting and crazy helpful. Is there a name for them or a collection of them somewhere?

**Comment by jlward** [comment]
https://blog.finxter.com/python-dunder-methods-cheat-sheet/

Long ago they we called "magic methods". But that was a poor name. They aren't magic. They are just operator overrides. So most folks call them "dunder methods". Dunder is short for "double underscore"

**Comment by jlward** [comment]
In general, it's safe to omit all of them. Until you need one. In order to make these sortable, we need `__lt__`. And in order to make them sumable, we need `__radd__`. So those are the two we are going to focus on. If we need more, we can add more. There are way more than I thought there were. I don't really use these too much in my day to day. Most of this stuff is handled by a DB. So we can just use that. But that doesn't mean it's not important to be aware they exist and how to use them.

**Comment by derekjamerson** [comment]
Should the score of a Player's hand be a property? After using the dunder methods, calculate_score looks a lot like a property. lol

**Comment by jlward** [comment]
> Should the score of a Player's hand be a property? After using the dunder methods, calculate_score looks a lot like a property. lol

It doesn't strictly speaking need to be a property. But it ought to be a property. The fact that you brought this up on your own leads me to believe you are seeing the benefit of properties :D
